### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by RekGRpth** [karlseguin/http.zig#1]
https://github.com/karlseguin/http.zig/blob/84d5c206d72b6a059427ffe15ceba351f318003b/readme.md?plain=1#LL53C17-L53C21 shoul be `req`?

**Comment by karlseguin** [comment]
Yup, thanks, fixed.

**Comment by RekGRpth** [comment]
> fixed

not yet: You should remove `_` too

**Comment by karlseguin** [comment]
Oh, you're right. I thought the variable wasn't being used. Changed it to log the URL at some point.
