### ISSUE TITLE
Support MIME type `application/wasm` 

### ISSUE THREAD

**Issue by jmrico01** [karlseguin/http.zig#18]
I can probably open a PR for this later today when I have some more time, but just wanted to write it down in case I forget. The `ContentType` enum in https://github.com/karlseguin/http.zig/blob/master/src/httpz.zig should have a `WASM` option, and the `forExtension` and other APIs should be enhanced to handle it.

Of course I can get around this now by adding the `Content-Type` header manually. Let me know if there is some specific criteria for which things should be in `ContentType`, or if it's just a convenience for common types.

**Comment by karlseguin** [comment]
Sure:
https://github.com/karlseguin/http.zig/commit/aace345f43c1e20c29c35304f7806b87181a07a0

**Comment by jmrico01** [comment]
Thank you!
