### ISSUE TITLE
Can this code be used in a GPL2 project?

### ISSUE THREAD

**Issue by nook24** [karlseguin/http.zig#22]
Hi,
unfortunately I'm not familiar with the MPL license and wanted to ask, if i can use this library in a GPLv2 project.

**Comment by karlseguin** [comment]
Yes, you can. MPL is "weak copyleft".  It's a bit like LGPL, but more permissive.

Only if you change source code of the library itself do you need to redistribute those changes.

**Comment by nook24** [comment]
Perfect! Many thanks
