### ISSUE TITLE
hash mismatch for websocket dependency

### ISSUE THREAD

**Issue by davo417** [karlseguin/http.zig#29]
https://github.com/karlseguin/http.zig/blame/69e9ab772080f3ce5d48a24cc88d7e49dff289ab/build.zig.zon#L7

**Comment by karlseguin** [comment]
> zig fetch https://github.com/karlseguin/websocket.zig/archive/328b8cba932d2a39da1ada6efe6001179a9c1aaa.tar.gz
12208afa05b6a3e0c16d5b21402a999f752203e974491e769a4c9831693f9fe101ed

I believe that's right. Is it possible you're victim to Zig's over-aggressive caching? `rm -fr zig-cache`

**Comment by davo417** [comment]
That was it, Thank you.
