### ISSUE TITLE
How to pass allocated data to response?

### ISSUE THREAD

**Issue by notramo** [karlseguin/http.zig#41]
I want to pass a dynamically formatted `Location` header URL into the response.
Since `response.header("Location", url);` does not copy the `url` value (it really should), I have to allocate it, but how to know when to deallocate to avoid memory leak?

**Comment by karlseguin** [comment]
This is what `res.arena` is for. It's an `std.mem.Allocator`.

I would agree with you that the header value should be copied, if there was a way to tell whether or not the value is a constant. But, without this ability, always copying would result in overhead for the common case where the key or value are constants.

**Comment by notramo** [comment]
Could you add this explanation to the README?

**Comment by karlseguin** [comment]
It already is:
https://github.com/karlseguin/http.zig?tab=readme-ov-file#header-value
