### ISSUE TITLE
Question: what is the url of htpz dependency

### ISSUE THREAD

**Issue by fprijate** [karlseguin/http.zig#43]
How do I get htpz dependency url for zig fetch command on win10 platform

**Comment by karlseguin** [comment]
Do you mean:

https://github.com/karlseguin/http.zig/archive/426ffd89155766a47ee4a307c9eb6f53ae63415d.tar.gz

This is a standard pattern for packages, just replace the commit with the one you want (`426ffd89155766a47ee4a307c9eb6f53ae63415d` is, at the time of this writing, the latest)
