### ISSUE TITLE
Crashed with `index out of bounds` error

### ISSUE THREAD

**Issue by coeuvre** [karlseguin/http.zig#50]
```
thread 36851 panic: index out of bounds: index 18446744073709551612, len 128
.../.cache/zig/p/12207952d04b655ac7c3b4086d022ee8d963cdbc4aee94b7b7e15e22ef82b2d4e317/src/worker.zig:895:33: 0x114f781 in wait
            .events = event_list[0..event_count],
                                ^
.../.cache/zig/p/12207952d04b655ac7c3b4086d022ee8d963cdbc4aee94b7b7e15e22ef82b2d4e317/src/worker.zig:117:40: 0x1131df9 in run
                var it = self.loop.wait(timeout) catch |err| {
                                       ^
.../zig-linux-x86_64-0.14.0-dev.244+0d79aa017/lib/std/Thread.zig:409:13: 0x110d823 in callFn__anon_12713
            @call(.auto, f, args);
            ^
.../zig-linux-x86_64-0.14.0-dev.244+0d79aa017/lib/std/Thread.zig:678:30: 0x10bd672 in entryFn
                return callFn(f, args_ptr.*);
                             ^
???:?:?: 0x7f6658fe2dec in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f6658fe2dec` was not available, trace may be incomplete

???:?:?: 0x7f66590660db in ??? (libc.so.6)
```

**Comment by karlseguin** [comment]
Sad. Sorry.

Can I know the OS and Zig version. Are there any special / reliable steps to reproduce it?

That slice length is coming from the result of an `epoll_pwait2` call.  That value looks like an -4 being cast to a u64, which suggest `EINTR`, but I don't see how that's coming out of the block.

**Comment by karlseguin** [comment]
I'm still not sure what's going on, but I tried to simplify the relevant code, depending only/directly on Zig's epoll_wait wrapper.

**Comment by coeuvre** [comment]
No need to sorry! Thanks for this awesome library!

I was using `zig-linux-x86_64-0.14.0-dev.244+0d79aa017` on archlinux and the error came out after I started the server, went away from the keyboard for minutes (so the compute went to sleep) and woke up the compute.

It's not easy to reproduce by let me try with the patch and get back to you.

**Comment by coeuvre** [comment]
Looks like the issue is fixed by https://github.com/karlseguin/http.zig/commit/7318f6f6a09df1a73532243c920ff5cafb03b2e0. Thanks!
