### ISSUE TITLE
Typo in key_value.zig

### ISSUE THREAD

**Issue by jmstevers** [karlseguin/http.zig#61]
Commit https://github.com/karlseguin/http.zig/commit/546610aad28cfceba5980834776c6edce724c3e8 causes http.zig to not compile. There is a typo on line 60 of `key_value.zig` where `lhs` is spelt `lha`.
```zig
return std.mem.eql(u8, lha, rhs);
```
should be
```zig
return std.mem.eql(u8, lhs, rhs);
```

**Comment by karlseguin** [comment]
Opps. Ya, fixed.

The nonblocking_ws branch, which will be merged soon, has github actions that would have caught that.

Sorry.
