### ISSUE TITLE
Implement stop waiting until all active handlers is done

### ISSUE THREAD

**Issue by StringNick** [karlseguin/http.zig#69]
When calling stop, waiting until all active handlers is done (or by timeout).
Current logic, he is just interrupt all job inside handler on server.stop() called

**Comment by karlseguin** [comment]
I agree. For now, no timeout though. After the last commit, I'm happy with the behavior in non-blocking mode (Linux/MacOS/BSD)...but blocking mode (windows) still needs some work.

**Comment by StringNick** [comment]
on macos works, thank you very much
