### ISSUE TITLE
Unable to build on mac m2 air 

### ISSUE THREAD

**Issue by ozzyozbourne** [karlseguin/http.zig#70]
Hi, i am trying to build the the project from source, when i run the zig build command it fails with the errors mention in the log file 
[error.log](https://github.com/user-attachments/files/16923715/error.log)

**Comment by karlseguin** [comment]
If you're using Zig 0.13, you need to use the [zig-0.13 branch](https://github.com/karlseguin/http.zig/tree/zig-0.13)

**Comment by ozzyozbourne** [comment]
Thanks you so much!

**Comment by luisnquin** [comment]
@karlseguin You'll save time by highlighting that information in the project's README file. :)
