### ISSUE TITLE
[Request]: Large file handling

### ISSUE THREAD

**Issue by Karitham** [karlseguin/http.zig#78]
I have a use-case where clients may send very large files (think larger than RAM).

Currently, `http.zig` reads the entire request in memory. This is problematic because an attacker could send a huge payload and OOM your application/server.

Similarly, when a client sends a large body for me to operate on, it would be great if instead of being read into memory, it could be turned into an `std.io.Reader` or a similar construct.

This would enable safety features (eg, refuse bodies larger than say 2MB), or would allow large files upload.

I am not proficient in the internals of said implementation, but that's how it works [in the go standard library](https://cs.opensource.google/go/go/+/master:src/net/net.go;l=124-179) and it's very powerful pattern.

**Comment by karlseguin** [comment]
Should be able to add this feature, but just to make sure, you still expect the client to send the correct Content-Length, yes? I want to make sure this isn't a request to also support Transfer-Encoding: chunked from the client.

**Comment by Karitham** [comment]
This looks fairly nice, maybe it would be even nicer if it implemented `std.io.Reader`? so `req.reader()` or `req.streamBody()` would return a reader which seems like the standard way to do reader. Unsure about the performance implications of that though.

I'm also wondering about the correctness (eg what happens when I forget to close the stream), but this seems like a decent start.

What are the disadvantages of having streaming by default? At worst having streaming by default means you would have to call some `readAll` or `readLimit` that returns a buffer owned by `http.zig`, which honestly sounds like a better API.

Even then, with an `std.io.Reader` all of the above are possible as well, and you can start to combine them further.

**Comment by karlseguin** [comment]
Ok, the API is a bit streamlined. No need to deinit, and it's an io.Reader. You now check `if (req.unread_body > 0)`.

```zig
// 5000 millisecond read timeout on a per-read basis
var reader = try req.reader(5000);
var buf: [4096]u8 = undefined;
while (true) {
    const n = try reader.read(&buf);
    if (n == 0) break
   // buf[0..n] is what was read
}
```

There's a few reasons why `req.reader()` won't become the default. 

The first is that, in its current implementation, `io.Reader` can have [surprising performance issues](https://github.com/ziglang/zig/issues/17985). For example, using `std.mem.indexOfScalar` on a `[]u8` can be orders of magnitude faster than the similar `reader.readUntilDelimiter()`.

The second has to do with httpz's architecture. Httpz uses a mix of an event loop and a thread pool. The full request is read in an nonblocking event loop, and then passed to a blocking thread pool.  Reading the body in the application's handler requires the read operation to become blocking (when you first call `req.reader()` the socket is put into blocking mode). This gives a nice and cohesive API, but it isn't the most efficient (you end up with threads waiting on I/O). So, keeping the default behavior as-is, where all the I/O is nonblocking, makes sense. If/when Zig async is re-introduced, all of this could change.

httpz generally assumes that most requests are going to be keepalive. So prematurely reading the body isn't the end of the world. Plus I generally assume most apps care about the body. Given all of the above, loading things directly in a `[]u8` (either the request buffer, or the large buffer pool), makes the most sense to me. BUT, I agree that having this flag to disable it for large sizes, is also important.

(We _have_ to read the body for keepalive, so as part of this commit, if `lazy_read_size` and the application doesn't stream the _whole_ body, httpz will do a final drain.)

**Comment by Karitham** [comment]
Thanks for these answers and the implementation, it looks great!
