### ISSUE TITLE
CORS middleware doesn't work

### ISSUE THREAD

**Issue by gyongph** [karlseguin/http.zig#81]
The issue is related to the pre-flight request mechanism. When a browser sends a cross-origin request, it first issues an OPTIONS request to the server to determine the CORS (Cross-Origin Resource Sharing) policy.

In this specific case, the problem lies in the following code:

 ```zig
var server = try httpz.Server(void).init(allocator, .{.port = 5882}, {});

// Middleware configuration for CORS handling
const cors = try server.middleware(httpz.middleware.Cors, .{
  .origin = "https://www.openmymind.net/",
});

// Apply CORS middleware globally to all routes (unless overridden)
var router = server.router(.{.middlewares = .{cors}});

// Alternatively, middleware can be added on a per-route basis
router.get("/v1/users", .{.middlewares = &.{cors}});

// To replace global middleware on specific routes, use the middleware_strategy
router.get("/v1/metrics", .{.middlewares = &.{cors}, .middleware_strategy = .replace});
```
The issue here is that the router.get method is designed to handle only specific HTTP methods (such as GET), but does not account for the OPTIONS method required for CORS pre-flight requests.

**Comment by karlseguin** [comment]
Setting the CORS middleware globally (the first option in the above code) should have this case. Specifically, the CORS middleware checks if the request is a OPTIONS **and** if the `sec-fetch-mode` header is set to `cors`. If so, it responds with a 204.

If you start to define the middleware on a route-by-route basis, then ya, you'll need to explicit define the OPTIONS route.

Are you seeing a different behavior?

(Side note: I realize that this code had 3 separate errors (!!!) which would all all prevent compilation. I've fixed the readme).

**Comment by gyongph** [comment]
```zig
var router = self.http_server.router(.{ .middlewares = &.{cors} });
                var group = router.group(path, .{});

**Comment by karlseguin** [comment]
It will work if the `sec-fetch-mode: cors` header is set.


```zig
    var server = try httpz.Server(void).init(allocator, .{ .port = PORT }, {});
    defer server.deinit();
    defer server.stop();
    const cors = try server.middleware(httpz.middleware.Cors, .{
        .origin = "https://www.openmymind.net/",
    });

    var router = server.router(.{.middlewares = &.{cors}});
    var group = router.group("/", .{});
    group.get("/", index, .{});
    try server.listen();
```


```txt
curl -X OPTIONS http://localhost:8806/ -H "sec-fetch-mode: cors"  -v
> OPTIONS / HTTP/1.1
> Host: localhost:8806
> User-Agent: curl/8.10.1
> Accept: */*
> sec-fetch-mode: cors
>
* Request completely sent off
< HTTP/1.1 204
< Access-Control-Allow-Origin: https://www.openmymind.net/
< Content-Length: 0
<
```

**Comment by gyongph** [comment]
the server.router() should be only called once because if it's called again it will modify the existing middleware right?

**Comment by karlseguin** [comment]
Yes.

If you have a complicated case, you might want to do something like:

```
router.options("/*", your_special_cors_handler, .{});
```
