### ISSUE TITLE
Windows 11 - GET requests pending after using SSE

### ISSUE THREAD

**Issue by 0x546F6D** [karlseguin/http.zig#84]
I have 3 basic html files with a css and/or js file attached to them.

After starting http.zig on windows, I have no problem loading and refreshing those pages.
However, after successfully requesting a server sent event from one of the pages, then those pages are not loading/refreshing anymore.
The html file is being transferred, but the state of the css or js files is shown as pending in chrome dev tool.
For the html file with both a js and a css file, only one of the js/css file is still pending, while both the html and the other js/css file are being transferred:
- if GET .css is requested before GET .js, then only the .js file is transferred.
- and vice-versa if GET .js is requested 1st.

It seems that it is the 1st GET request right after the html transfer that ends up pending.

While opening 2 browsers and having one pending after using SSE, I can still continue requesting as many server sent events as I want from the other browser.

I checked on wireshark on top of firefox/chrome, and all the GET requests are visible (GET /index.html, GET /styles.css, etc..).
Before using the server sent event, http.zig respond to all the request, which is shown in wireshark and confirmed by some debug prints, but after using server sent events, the response to some of the GET requests is neither visible in wireshark, nor logged in any debug print.

Could it be because of the blocking mode on windows? Is there a simple SSE example that I could modify to test if the problem comes from my implementation? I am testing on my own laptop using localhost btw.

**Comment by karlseguin** [comment]
I do assume it has something to do with blocking mode. Gonna look into it. Are you on master or the zig-0.13 branch?

**Comment by karlseguin** [comment]
I can reproduce the issue on master.

**Comment by 0x546F6D** [comment]
I am currently on master, and sorry for reporting yet another issue on windows.

**Comment by karlseguin** [comment]
Thanks for the detailed report, I was able to reproduce it. Was confusing for a second, but I believe the latest commit fixes the issue. 

Curious about your use of Windows. Is it just for development, or are you deploying something on Windows as well?

**Comment by 0x546F6D** [comment]
I just zig fetched the latest commit and indeed, the issue is now fixed. Thanks a lot for the "blazingly" fast response :)


My field of expertise is a bit niche, working with electrical/automation engineers.
We would like to develop some custom tools for our teams of engineers, who spend half of their time out of the office: commissioning sites, often in the middle of nowhere, without any proper internet.
The goal is to develop an online version of our tools, deployed on our linux server, that our engineers can access when they are in the office; and to use a solution like [zig-webui](https://github.com/webui-dev/zig-webui) to produce an offline version of the same tools (hence using very similar codebase), that they can use on their windows laptops when they are on site.


A lot of electrical engineers are not very familiar with linux, and even if they were, the biggest companies in our field (Siemens, Schneider, GE, ABB, etc..) mostly develop tools for windows; so changing their laptops to a linux machine is unfortunately out of the question. Hence why the need to deploy on windows :)

**Comment by karlseguin** [comment]
The thread-per-connection approach that blocking mode (windows) uses should be fine then (minus the bugs!)
